baseURL = 'https://trinteen.github.io/'
languageCode = "cz-cs"
title = "MY LIFE IS ZEROS AND ONES"
theme = "hugo-theme-stack"
sectionPagesMenu = "main"
pluralizelisttitles = "false"

[params]
    homeSubtitle = "Oficiální stránky jednoho \"Ajťáka\" co počítačem a technikou žije."
    customJS = ["/mod.js"]
    [params.logo]
        logoText = "Trinteen.CZ"
        logoCursorColor = "red"


[taxonomies]
  tag = "tags"
  category = "categories"

