baseURL = 'https://trinteen.github.io/'
languageCode = "cz-cs"
title = "MY LIFE IS ZEROS AND ONES"
theme = "hacker"
sectionPagesMenu = "main"
pluralizelisttitles = "false"
timeout = 180000

[params]
    homeSubtitle = "Oficiální stránky jednoho \"Ajťáka\" co počítačem a technikou žije."
    customJS = ["/mod.js"]
    [params.logo]
        logoText = "Trinteen.CZ"
        logoCursorColor = "red"


[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

